DROP TABLE coords;
DROP TABLE countries;
DROP TABLE conferences;

CREATE TABLE coords(
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  lat VARCHAR(25) NOT NULL,
  lng VARCHAR(25) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE countries(
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(80) NOT NULL,
  coord_id INTEGER UNIQUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (coord_id) REFERENCES coords(id) ON DELETE CASCADE
);

CREATE TABLE conferences(
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  event_date DATETIME NOT NULL,
  coord_id INTEGER UNIQUE,
  country_id INTEGER,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (coord_id) REFERENCES coords(id) ON DELETE CASCADE,
  FOREIGN KEY (country_id) REFERENCES countries(id) ON DELETE SET NULL
);

INSERT INTO coords (lat, lng) VALUES
 (
    '50.448091856566556',
    '30.525033849212527'
 ),
 (
    '47.83846817909879',
    '35.138939112399264'
 ),
 (
    '47.826158506197494',
    '35.16676034248282'
 );

INSERT INTO countries (name, coord_id) VALUES
 ('Ukraine', 1);

INSERT INTO conferences (name, event_date, coord_id, country_id) VALUES 
('Conference1', NOW() + INTERVAL 5 DAY, 2, 1),
('Conference2', NOW() + INTERVAL 10 DAY, 3, 1);
